services:
  backend:
    build: ./backend
    container_name: paytrust_backend
    env_file: .env
    restart: always
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: payroll
      POSTGRES_PASSWORD: payroll123
      POSTGRES_DB: paytrust

  nginx:
    image: nginx:alpine
    container_name: paytrust_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
